use_frameworks!

platform :ios, '12.0'

target 'EnolaGay_Example' do

  pod 'EnolaGay', :path => '../'
  pod 'Cache'
  pod 'Alamofire', '~> 4.9.0'

  target 'EnolaGay_Tests' do
    inherit! :search_paths

    
  end
end
