source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'Demo' do

  pod 'EnolaGay/EMERANA', :path => '../'
  pod 'EnolaGay/Logger', :path => '../'
  pod 'EnolaGay/CircularProgressView', :path => '../'
  pod 'EnolaGay/TextFieldEffects', :path => '../'
  pod 'EnolaGay/GiftMessageCtrlPanel' , :path => '../'
  pod 'EnolaGay/JudyPopBubble' , :path => '../'
  pod 'EnolaGay/JudyWaterWaveView' , :path => '../'
  
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'

  pod 'EnolaGay/KeyboardHelper', :path => '../'

  pod 'Cache'
  pod 'IGListKit'

  #  pod 'EnolaGay/TextFieldEffects', :path => '../'
  #  pod 'EnolaGay/JudyPopBubble', :path => '../'
  #  pod 'EnolaGay/JudyPlusButtonTabBar', :path => '../'
  #  pod 'EnolaGay/JudyWaterWaveView', :path => '../'
  #  pod 'EnolaGay/MarqueeView', :path => '../'
  #  pod 'EnolaGay/WKWebView', :path => '../'
  
  #  target 'EnolaGay_Tests' do
  #    inherit! :search_paths
  #  end

  # MARK: - 在该工程中为 target 额外安装 pod，并同时拥有主工程中的 pod.
  
  # MARK: EMERANA
  
  target 'EMERANA' do
    pod 'IQKeyboardManagerSwift'
    
    #    pod 'MBProgressHUD'
    pod 'SwiftMessages'
    pod 'MJRefresh'
    pod 'SDWebImage'
    #  广告轮播图
    # pod 'SDCycleScrollView'
    
    #    pod 'SocketRocket'    # https://github.com/facebook/SocketRocket.git
    #    pod 'RESideMenu', '~> 4.0.7' #侧边菜单
    #    pod 'ResponseDetective'
    #    pod 'DeviceKit', '~> 1.3'
    pod 'SwiftyUserDefaults', '5.0.0-beta.5'
    pod 'DZNEmptyDataSet'

#    pod 'FMDB'
    pod 'Alamofire'
    pod 'BadgeHub'
    pod 'SwiftyJSON'
    
  end
  
end


# MARK: - 独立为 target 安装 pod，不继承主工程已安装的 pod.


# MARK: PickerDemo
target 'PickerDemo' do
  pod 'EnolaGay/HPickerView', :path => '../'
end

# MARK: HUD
target 'HUD' do
  platform :ios, '13.0'

  pod 'EnolaGay/HUD', :path => '../'
end


# MARK: PlayerDemo

target 'PlayerDemo' do
  platform :ios, '12.0'

  pod 'EnolaGay', :path => '../'
  pod "Player"

end


# MARK: RefreshAdapter

target 'RefreshAdapter' do
  pod 'EnolaGay', :path => '../'
  pod 'MJRefresh'
end


## MARK: AGUL
#
#target 'AGUL' do
#  pod 'EnolaGay', :path => '../'
##  pod 'EnolaGay/MarqueeView', :path => '../'
#  
#  pod 'Kingfisher'
#  pod 'SwiftMessages'
#  pod 'SDWebImage'
#end
