source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'Demo' do
  pod 'EnolaGay', :path => '../'
  pod 'EnolaGay/EMERANA', :path => '../'
  pod 'EnolaGay/Logger', :path => '../'
  pod 'EnolaGay/CircularProgressView', :path => '../'
  
  #  pod 'EnolaGay/TextFieldEffects', :path => '../'
  #  pod 'EnolaGay/JudyPopBubble', :path => '../'
  #  pod 'EnolaGay/JudyPlusButtonTabBar', :path => '../'
  #  pod 'EnolaGay/JudyWaterWaveView', :path => '../'
  #  pod 'EnolaGay/MarqueeView', :path => '../'
  #  pod 'EnolaGay/WKWebView', :path => '../'
  
  #  target 'EnolaGay_Tests' do
  #    inherit! :search_paths
  #  end

  # MARK: - 在该工程中为 target 额外安装 pod，并同时拥有主工程中的 pod.
  
  # MARK: EMERANA
  
  target 'EMERANA' do
    pod 'IQKeyboardManagerSwift'
    
    #    pod 'MBProgressHUD'
    pod 'SwiftMessages'
    pod 'MJRefresh'
    pod 'SDWebImage'
    #  广告轮播图
    # pod 'SDCycleScrollView'
    
    #    pod 'SocketRocket'    # https://github.com/facebook/SocketRocket.git
    #    pod 'RESideMenu', '~> 4.0.7' #侧边菜单
    #    pod 'ResponseDetective'
    #    pod 'DeviceKit', '~> 1.3'
    pod 'SwiftyUserDefaults', '5.0.0-beta.5'
    pod 'DZNEmptyDataSet'

    pod 'FMDB'
    pod 'Alamofire'
    pod 'BadgeHub'
    pod 'SwiftyJSON'
    
  end
  
end


# MARK: - 独立为 target 安装 pod，不继承主工程已安装的 pod.

# MARK: ToastDemo

target 'ToastDemo' do
  pod 'EnolaGay', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'

end

# MARK: PickerDemo
target 'PickerDemo' do
  pod 'EnolaGay/HPickerView', :path => '../'
  pod 'EnolaGay/SegmentedView', :path => '../'
end

# MARK: HUD
target 'HUD' do
  platform :ios, '13.0'

  pod 'EnolaGay/HUD', :path => '../'
end

# MARK: VersionCheck

target 'VersionCheck' do
  pod 'EnolaGay/EMERANA', :path => '../'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
end


# MARK: CacheDemo

target 'CacheDemo' do
  pod 'EnolaGay/EMERANA', :path => '../'
  pod 'Cache'
end


# MARK: PlayerDemo

target 'PlayerDemo' do
  platform :ios, '12.0'

  pod "Player"

  pod 'EnolaGay/EMERANA', :path => '../'

end


# MARK: RefreshAdapter

target 'RefreshAdapter' do
  pod 'EnolaGay', :path => '../'
  pod 'MJRefresh'
  pod 'Alamofire'
end


# MARK: KeyBoardPop

target 'KeyBoardPop' do
  pod 'EnolaGay/Logger', :path => '../'
  pod 'EnolaGay/KeyboardHelper', :path => '../'
end


# MARK: CastSurelyCalculation

target 'CastSurelyCalculation' do
  pod 'EnolaGay/EMERANA', :path => '../'
end

# MARK: GifEffectsDemo 送礼物控制面板、烟花爆炸特效

target 'GifEffectsDemo' do
  pod 'EnolaGay/EMERANA' , :path => '../'
  pod 'EnolaGay/GiftMessageCtrlPanel' , :path => '../'
  pod 'EnolaGay/JudyPopBubble' , :path => '../'
  
end


# MARK: JudyLivePageViewCtrl

target 'JudyLivePageViewCtrl' do
  pod 'EnolaGay/EMERANA', :path => '../'
end

## MARK: AGUL
#
#target 'AGUL' do
#  pod 'EnolaGay', :path => '../'
##  pod 'EnolaGay/MarqueeView', :path => '../'
#  
#  pod 'Kingfisher'
#  pod 'SwiftMessages'
#  pod 'SDWebImage'
#end


# MARK: MyIGListKit

target 'MyIGListKit' do
  pod 'EnolaGay/Logger', :path => '../'
  pod 'IGListKit', '~> 4.0.0'
end
